Rework

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -20,52 +20,43 @@ runs:
       run: |
         # Convert newlines to spaces
         PACKAGES=$(echo "${{ inputs.packages }}" | tr '\n' ' ')
-
-        DEST="$HOME/.gap/pkg"
-        mkdir -p "$DEST"
-
+     
         if [ "$RUNNER_OS" = "Windows" ]; then
-          # Convert Windows path (D:\...) to Cygwin path (/cygdrive/d/...)
-          TMPROOT=$(cygpath -u "$RUNNER_TEMP")
+          DEST="$HOME/_gap/pkg"
+          TMPDIR=$(cygpath -u "$RUNNER_TEMP/install-pkg")
         else
-          TMPROOT="$RUNNER_TEMP"
+          DEST="$HOME/.gap/pkg"
+          TMPDIR="$RUNNER_TEMP/install-pkg"
         fi
-        TMPDIR="$TMPROOT/install-pkg"
+        
+        mkdir -p "$DEST"
         mkdir -p "$TMPDIR"
         
         PKG_DISTRO="$TMPDIR/package-infos.json"
-        
         WGET_HEADER="Authorization: token ${{ github.token }}"
-        echo "Headers: $WGET_HEADER"
 
-        TAR="bsdtar"
-
-        ############################################
-        install_from_archive() {
-          url="$1"
-          target="$2"
-
-          filename=$(basename "$url")
-          archive="$TMPDIR/$filename"
-
-          echo "Downloading $url"
-        
-          wget -O "$archive" "$url"
+        ##### BEGIN HELPER FUNCTIONS #####
+        # Download archive and extract to folder
+        download_and_extract() {
+          local url="$1"
+          local filename=$(basename "$url")
+          local target="$2"
           
+          echo "Installing $filename at $target."
+          
+          local archive="$TMPDIR/$filename"
+          wget -qO "$archive" "$url"
           mkdir -p "$target"
-          $TAR -xf "$archive" -C "$target"
-          ls -a $target
-
-          echo "Checking $DEST" for files?
-          ls -a $DEST
+          bsdtar -xf "$archive" -C "$target"
+          rm "$archive"
         }
-
-        ############################################
+        
+        # Create valid archive url from base url and possible formats
         prefer_archive() {
-        
-          base="$1" # base URL without extension
-          formats="$2" # newline-separated list of available archive formats
-        
+          local base="$1"
+          local formats="$2" # newline-separated list
+
+          # Prefer .tar.gz if available
           if echo "$formats" | grep -q "^\.tar\.gz$"; then
             echo "${base}.tar.gz"
           elif echo "$formats" | grep -q "^\.tar\.bz2$"; then
@@ -73,85 +64,36 @@ runs:
           elif echo "$formats" | grep -q "^\.zip$"; then
             echo "${base}.zip"
           else
-            echo "No supported archive format found"
+            echo "::error::No supported archive format found"
             exit 1
           fi
         }
 
-        ############################################
-        install_from_packageinfo() {
-        
-          info="$1"
-          target="$2"
-        
-          if [ ! -f "$info" ]; then
-            echo "package-info.json not found: $info"
-            exit 1
-          fi
-        
-          archive_base=$(jq -r '.ArchiveURL' "$info")
-          formats=$(jq -r '.ArchiveFormats' "$info")
-          formats=$(echo "$formats" | tr ' ' '\n')
-          archive_url=$(prefer_archive "$archive_base" "$formats")
-          echo "Downloading package archive: $archive_url"
-        
-          install_from_archive "$archive_url" "$target"
+        # Get package name
+        get_pkg_name() {
+          local base=$(basename "$1")
+      
+          # Remove archive suffix
+          base=$(echo "$base" | sed -E 's/\.(tar\.gz|tar\.bz2|zip)$//')
+          # Remove version suffix
+          base=$(echo "$base" | sed -E 's/-[0-9]+(\.[0-9]+)*$//')
+          # Convert to lowecase
+          name=$(echo "$base" | tr '[:upper:]' '[:lower:]')
         }
 
-        ############################################
-        github_latest_tag() {
-          repo="$1"
-          wget --header="$WGET_HEADER" -O- "https://api.github.com/repos/$repo/releases/latest" \
-            | jq -r '.tag_name'
-        }
-
-        ############################################
-        github_release_tags() {
-          repo="$1"
-          wget --header="$WGET_HEADER" -O- "https://api.github.com/repos/$repo/releases" \
-            | jq -r '.[].tag_name'
-        }
-
-        ############################################
-        find_release_for_version() {
-          repo="$1"
-          version="$2"
-
-          github_release_tags "$repo" \
-            | sed 's/^v//' \
-            | sort -V \
-            | awk -v v="$version" '$0>=v {print; exit}'
-        }
-
-        ############################################
-        install_from_repo() {
-        
-          repo="$1"
-          version="$2"
-          target="$3"
-        
-          # If version is "latest", treat as empty
+        # Get archive URL
+        get_archive_url() {
+          local repo="$1"
+          local version="$2"
+          
           if [ "$version" = "latest" ]; then
-            version=""
-          fi
-        
-          # If version is "dev" or "devel", clone default branch
-          if [ "$version" = "dev" ] || [ "$version" = "devel" ]; then
-            echo "Cloning development branch of $repo"
-            git clone "https://github.com/$repo.git" "$target"
-            return
-          fi
-        
-          if [ -z "$version" ]; then
             echo "Fetching latest release for $repo"
-            wget --header="$WGET_HEADER" -O "$TMPDIR/release.json" \
-              "https://api.github.com/repos/$repo/releases/latest"
+            wget --header="$WGET_HEADER" -qO "$TMPDIR/release.json" "https://api.github.com/repos/$repo/releases/latest"
           else
-            echo "Selecting release >= $version"
-            wget --header="$WGET_HEADER" -O "$TMPDIR/releases.json" \
-              "https://api.github.com/repos/$repo/releases"
+            echo "Selecting oldest release >= $version"
+            wget --header="$WGET_HEADER" -qO "$TMPDIR/releases.json" "https://api.github.com/repos/$repo/releases"
         
-            release=$(jq -c --arg v "$version" '
+            local release=$(jq -c --arg v "$version" '
               map(. + {ver:(.tag_name|sub("^v";""))})
               | sort_by(.ver)
               | map(select(.ver >= $v))
@@ -159,145 +101,146 @@ runs:
             ' "$TMPDIR/releases.json")
         
             if [ "$release" = "null" ] || [ -z "$release" ]; then
-              echo "No release >= $version found"
+              echo "::error::No release >= $version found"
               exit 1
             fi
         
             echo "$release" > "$TMPDIR/release.json"
+            rm "$TMPDIR/releases.json"
           fi
-        
-          echo "Locating package-info.json asset"
-        
-          asset_url=$(jq -r '
+          
+          local asset_url=$(jq -r '
             .assets[]
             | select(.name=="package-info.json")
             | .browser_download_url
           ' "$TMPDIR/release.json")
-        
+          rm "$TMPDIR/release.json"
+
           if [ -z "$asset_url" ] || [ "$asset_url" = "null" ]; then
-            echo "package-info.json asset not found"
+            echo "::error::Release has no package-info.json asset"
             exit 1
           fi
-        
-          echo "Downloading package-info.json"
-          wget -O "$TMPDIR/package-info.json" "$asset_url"
-        
-          echo "Resolving archive from package-info.json"
-          install_from_packageinfo "$TMPDIR/package-info.json" "$target"
+
+          local info="$TMPDIR/package-info.json"
+          wget -qO "$info" "$asset_url"
+
+          local archive_base=$(jq -r '.ArchiveURL' "$info")
+          local formats=$(jq -r '.ArchiveFormats' "$info")
+          formats=$(echo "$formats" | tr ' ' '\n')
+
+          version_sel=$(jq -r '.Version' "$info")
+          echo "Given version: $version | Selected version: $version_sel"
+          archive_url=$(prefer_archive "$archive_base" "$formats")
+          
+          rm "$info"
         }
 
-        ############################################
-        load_package_distro() {
+        # Get PackageDistro information
+        get_package_distro() {
           if [ ! -f "$PKG_DISTRO" ]; then
-        
-            url="https://github.com/gap-system/PackageDistro/releases/download/latest/package-infos.json.gz"
-        
-            echo "Downloading package list from $url"
-        
-            wget -O "$TMPDIR/package-infos.json.gz" "$url" || {
-              echo "Failed to download package-infos.json.gz"
-              exit 1
-            }
-        
-            echo "Extracting package-infos.json"
-        
-            gunzip -v "$TMPDIR/package-infos.json.gz" || {
-              echo "gunzip failed"
-              exit 1
-            }
-        
+            echo "Downloading packages-infos.json from PackageDistro"
+            local distro="$TMPDIR/package-infos.json.gz"
+            wget -qO "$distro" "https://github.com/gap-system/PackageDistro/releases/download/latest/package-infos.json.gz"
+            gunzip "$distro"
             if [ ! -s "$PKG_DISTRO" ]; then
-              echo "package-infos.json extraction failed"
+              echo "::error::Could not download PackageDistro json"
               exit 1
             fi
           fi
         }
 
-        ############################################
-        install_from_name() {
+        # Get repository name from package name using PackageDistro
+        get_repo_from_name() {
+          local name="$1"
         
-          name="$1"
-          version="$2"
-          target="$3"
+          get_package_distro
         
-          load_package_distro
-        
-          pkg=$(jq -c --arg n "$name" '.[$n]' "$PKG_DISTRO")
+          local pkg=$(jq -c --arg n "$name" '.[$n]' "$PKG_DISTRO")
         
           if [ "$pkg" = "null" ] || [ -z "$pkg" ]; then
-            echo "Package $name not found"
+            echo "::error::Package $name not found in PackageDistro"
             exit 1
           fi
         
-          distro_version=$(echo "$pkg" | jq -r '.Version // empty')
-        
-          if [ -z "$version" ] || [ "$version" = "$distro_version" ]; then
-        
-            archive_base=$(echo "$pkg" | jq -r '.ArchiveURL')
-            formats=$(echo "$pkg" | jq -r '.ArchiveFormats')
-            formats=$(echo "$formats" | tr ' ' '\n')
-        
-            archive_url=$(prefer_archive "$archive_base" "$formats")
-            install_from_archive "$archive_url"
-        
-          else
-            # "dev"/"devel" or other version → install from repo
-            repo=$(echo "$pkg" | jq -r '.SourceRepository.URL')
-            repo=${repo#https://github.com/}
-        
-            echo "Using repository $repo"
-            install_from_repo "$repo" "$version" "$target"
-          fi
+          # Don't try to get URL from PackageDistro - latest version not be merged yet!
+          local repo_url=$(echo "$pkg" | jq -r '.SourceRepository.URL') || {
+            echo "::error::Package $name not found in PackageDistro"
+            exit 1
+          }
+          repo=${repo_url#https://github.com/}
+
         }
 
-        #####################
+        # Use GAP to check if package-version combination is already installed
+        check_pkg_availability() {
+          local pkg="$1"
+          local ver="$2"
+          gap -A -q <<GAPINPUT
+            QuitGap( TestPackageAvailability( "$pkg", "$ver" ) <> fail );
+        GAPINPUT
+          return $?
+        }
 
+        # Build package
         build_pkg() {
-          
           echo "TODO - build package here"
         }
 
-        strip_archive_suffix() {
-          echo "$1" | sed -E 's/\.(tar\.gz|tar\.bz2|zip)$//'
-        }
-
-        check_pkg_availability() {
-          pkg="$1"
-          ver="$2"
-          gap <<GAPINPUT
-            QuitGap( TestPackageAvailability( "$pkg", "$ver" ) <> fail );
-        GAPINPUT
-        }
-
-        ############################################
+        ##### END HELPER FUNCTIONS #####
         for pkg in $PACKAGES; do
-          echo "Now handling $pkg"
-        
+          echo "::group::Installing $pkg"
+          
           version="latest"
-        
           if [[ "$pkg" == *@* ]]; then
             version="${pkg##*@}"
             pkg="${pkg%@*}"
           fi
           
-          base=$(basename "$pkg")
-          name=$(strip_archive_suffix "$base")
-          name=$(echo "$name" | tr '[:upper:]' '[:lower:]')
+          get_pkg_name "$pkg"
           pkgdir="$DEST/$name"
 
-          echo "Getting package $name with version $version into dir $pkgdir"
-         
           if [[ "$pkg" =~ ^https?://.*\.(tar\.gz|tar\.bz2|zip)$ ]]; then
-            echo "Detected archive"
-            install_from_archive "$pkg" "$pkgdir"
-          elif [[ "$pkg" =~ .*/.* ]]; then
-            echo "Detected repository"
-            install_from_repo "$pkg" "$version" "$pkgdir"
+            echo "Input is an archive"
+            download_and_extract "$pkg" "$pkgdir"
           else
-            echo "Detected package name"
-            install_from_name "$name" "$version" "$pkgdir"
+            # Check if package is already available
+            if [ "$version" != "latest" ] && [ "$version" != "devel" ]; then
+              if check_pkg_availability $name $version; then
+                echo "Package $name $version is already available, skipping."
+                continue
+              else
+                echo "Package $name $version not yet available, installing."
+              fi
+            fi
+
+            if [[ "$pkg" =~ .*/.* ]]; then
+              echo "Input is a package repository"
+              repo="$pkg"
+            else
+              echo "Input is a package name"
+              get_repo_from_name $name
+            fi
+
+            if [ "$version" = "devel" ]; then
+              echo "Cloning development branch of $repo"
+              git clone "https://github.com/$repo.git" "$pkgdir"
+            else
+              get_archive_url "$repo" "$version"
+              
+              # Another availability check, this time for latest version
+              if [ "$version" = "latest" ]; then
+                if check_pkg_availability $name $version_sel; then
+                  echo "Package $name $version_sel is already available, skipping."
+                  continue
+                else
+                  echo "Package $name $version_sel not yet available, installing."
+                fi
+              fi
+              
+              download_and_extract "$archive_url" "$pkgdir"
+            fi
           fi
-        
+          
           echo "Building package in $pkgdir"
         
           (
@@ -306,7 +249,6 @@ runs:
               exit 1
             }
             echo "now inside $pkgdir"
-            ls -a .
             build_pkg
           )
         
